apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: app
spec:
  type: NodePort
  ports:
    - name: server
      port: 55555
      targetPort: 55555
      protocol: TCP
  selector:
    app: server
